image:
  file: .gitpod.Dockerfile
ports:
  - port: 4040 # spark
    onOpen: open-preview
#   - port: 8888 # jupyter
#     onOpen: open-preview
# tasks:
#   - command: >
#       jupyter notebook --port=8888
